services:
    uecode.api_key.provider.user_provider:
        class: Uecode\Bundle\ApiKeyBundle\Security\Authentication\Provider\UserProvider
        arguments: ["@fos_user.user_manager"]
    uecode.api_key.provider.email_user_provider:
        class: Uecode\Bundle\ApiKeyBundle\Security\Authentication\Provider\EmailUserProvider
        arguments: ["@fos_user.user_manager"]
    uecode.api_key.provider.api_key:
        class: Uecode\Bundle\ApiKeyBundle\Security\Authentication\Provider\ApiKeyProvider
        arguments: [""]
    uecode.api_key.listener.api_key:
        class: Uecode\Bundle\ApiKeyBundle\Security\Firewall\ApiKeyListener
        arguments: ["@security.token_storage", "@security.authentication.manager", "@uecode.api_key.extractor"]
    uecode.api_key.extractor.query:
        class: Uecode\Bundle\ApiKeyBundle\Extractor\QueryExtractor
        arguments: [%uecode.api_key.parameter_name%]
    uecode.api_key.extractor.header:
        class: Uecode\Bundle\ApiKeyBundle\Extractor\HeaderExtractor
        arguments: [%uecode.api_key.parameter_name%]
    uecode.api_key.generator:
        class: Uecode\Bundle\ApiKeyBundle\Util\ApiKeyGenerator
